services:
  travelyo.response_listener:
      class: danrevah\SandboxBundle\EventListener\SandboxListener
      arguments: [@kernel, @request_stack]
      tags:
          - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }