install:
  - composer install
  - composer require symfony/framework-bundle:2.6
  - composer require symfony/expression-language
  - composer require doctrine/common

before_script:
  - mkdir -p build/logs

script:
  - phpunit --coverage-clover=coverage.clover

