language: php

php:
  - 5.6
  - 5.5
  - 5.4
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
    - php: 5.4
  fast_finish: true

env:
  - SYMFONY_VERSION="2.4.*" DB=mysql
  - SYMFONY_VERSION="2.5.*" DB=mysql
  - SYMFONY_VERSION="2.6.*" DB=mysql
  - SYMFONY_VERSION="2.7.*" DB=mysql

install:
  - composer self-update
  - composer install
  - composer require symfony/framework-bundle:${SYMFONY_VERSION}
  - composer require symfony/expression-language
  - composer require doctrine/common

before_script:
  - mkdir -p build/logs

script:
  - phpunit --coverage-clover build/logs/clover.xml

after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php phpunit && wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover tmp/coverage.clover; fi;'